# Generated by Django 6.0.2 on 2026-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('areaofspecialization', models.CharField(max_length=25)),
                ('Telno', models.IntegerField()),
            ],
        ),
    ]
